spring:
  application:
    name: cloudbalance

  datasource:
    url: jdbc:mysql://localhost:3306/cloudbalance
    username: root
    password: Rishu@1204
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

snowflake:
  account: YFYRZGG-BWB35436
  username: ro_user
  password: fRe$her@b00tc@mp2025
  warehouse: COMPUTE_WH
  database: aws
  schema: cost